### ISSUE TITLE
Proxy Redirect to Request Specific Notebooks?

### ISSUE THREAD

**Issue by mmcky** [jupyter/tmpnb#155]
This is a great project! I would like to be able to specify a notebook directly such that the proxy server forwards the reference - links with a container - and opens at the requested notebook:

```
http://127.0.0.1:8000/notebooks/some_notebook.ipynb
```

When ``tmpnb`` assigns a container ``/user/<hash>/`` the proxy could forward the notebook request ``notebooks/some_notebook.ipynb`` and then ``orchestrate.py`` could pair with a container and attach the requested notebook path to open the specific ``ipynb``. 

Is this currently possible? 
I would be happy to work on this functionality - just don't want to reinvent the wheel and couldn't immediately see this in the docs. 

Also I am not sure if this belongs here or in ``jupyter/configurable-http-proxy``. Given the proxy server faces externally it may be the best repo to track this request. 

[Label: Feature Request]

**Comment by rgbkrk** [comment]
If this is for your own tmpnb deployment with your own setup, the argument you pass to `orchestrate.py` is `--redirect_uri` with the path you want (it defaults to `/tree`). In this case you'd want `orchestrate.py --redirect_uri='notebooks/some_notebook.ipynb'`

However, it sounds like you want for a user that hits your given tmpnb server to redirect with that notebook running:

```
https://mytmpnb/notebooks/1.ipynb --> https://mytmpnb/user/adfe/notebooks/1.ipynb
```

People have definitely asked for that and I've held back on implementing it (myself) solely because I want to steer clear of possible XSS avenues. It's totally fine if you submit a PR for it though and make it not default behavior (configurable somehow).

**Comment by mmcky** [comment]
If I understand ``--redirect_uri`` correctly - it's a one shot setting - all requests made to the running cluster of containers will serve the same notebook. 

Your redirect example is exactly right - in that I would like dynamic forwarding of a requested notebook through the proxy assignment stage. The use case I am thinking about is to have a separate deployment and have links embedded in a lecture such that a student can click on the link and be directed to running notebook that contains the executable code straight away in a new tab. The server side would then ``garbage`` collect idle instances. 

I will have a more considered think about how this might be done and put together a proposal.
