### ISSUE TITLE
Modifying the path of tmpnb

### ISSUE THREAD

**Issue by achapkowski** [jupyter/tmpnb#235]
Hello,

I want to create a tmpnb for a class I am running, but I don't know where I should put the custom python packages.  I am using anaconda3 install, and I have a server running internal on RHEL 7.0.

When I type:
`import sys`
`sys.path`

I get the following:

```
['',
 '/opt/conda/lib/python35.zip',
 '/opt/conda/lib/python3.5',
 '/opt/conda/lib/python3.5/plat-linux',
 '/opt/conda/lib/python3.5/lib-dynload',
 '/opt/conda/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg',
 '/opt/conda/lib/python3.5/site-packages',
 '/opt/conda/lib/python3.5/site-packages/IPython/extensions',
 '/home/jovyan/.ipython']
```

How do I change the path, or add to it?  It won't allow me to use numpy or pandas as well.

Thank you

**Comment by captainsafia** [comment]
Hello, @achapkowski! Thanks for opening the issue. If you are trying to install Python packages within the tmpnb image that is running, you will need to edit the `Dockerfile` and add commands to install each of these packages. If you'd like me to clarify, let me know!

**Comment by achapkowski** [comment]
@captainsafia please do expand on this I'm new to this.

**Comment by captainsafia** [comment]
@achapkowski — Sure, no problem! Excuse me if I present information you already know, I'm gonna try and cover all the bases.

So, tmpnb leverages Docker, which is a service that allows you to create "containers" of prepackaged applications and their dependencies. How do you tell Docker what to put in this containers? Through a Dockerfile. If you take a look at the [Dockerfile used by tmpnb](https://github.com/jupyter/tmpnb/blob/master/Dockerfile), you will notice that it starts off by using the Debian Wheezy operating system with Python 3.4 setup (line 1). It then installs some Python and SSL related dependencies (lines 3-4) then installs whatever is defined in the [requirements.txt](https://github.com/jupyter/tmpnb/blob/master/requirements.txt) using `pip`. In the end, you get a container that contains a Linux environment with a basic Python setup.

You can't really use an existing installation of Python that is on your machine because the container is a VM on a separate machine. What you can do is create your own Dockerfile. So let's say you wanted a container for your students that contained Python 3 and a `pandas` installation, it would look something like this.

```
FROM python:3.4-wheezy

RUN apt-get update && apt-get install python-dev libcurl4-openssl-dev -y
RUN pip install --upgrade pip

RUN mkdir -p /srv/tmpnb
WORKDIR /srv/tmpnb/

RUN pip install pandas

# Now copy in everything else
COPY . /srv/tmpnb/

ENV DOCKER_HOST unix://docker.sock

CMD python orchestrate.py
```

So here are the steps that you would take to deploy an image for your students.
1. Identify what specific packages you would like installed in the ecosystem. If you would like to create a `requirements.txt` with **all** of the packages installed on your system you can run `pip freeze > requirements.txt`.
2. Clone the tmpnb repository.
3. Copy the output of your `requirements.txt` into the `requirements.txt` in the clone directory.
4. Run `docker build .` to build an image (you can think of this as a virtual machine image) from the instructions described in the Dockerfile.
5. Run `docker images` to get the name of the image that was just created. You can determined which one it is by checking the `CREATED` attribute in the table.
6. Follow the directions under the "Launching with your own Docker images" section in the README.

Let me know if you would like me to clarify anything!

**Comment by achapkowski** [comment]
@captainsafia great information.  If users created their own package during lessons and are not accessible by pip, is there a way to add those packages to the tmpnb?

Or is this done when you do the copy?

**Comment by achapkowski** [comment]
When I build my Dockerfile using the following command:

 `docker build -t="custom/minimal-notebook:v2" ./minimal-notebook`

I am getting the following error:
```
Step 27 : COPY start-notebook.sh /usr/local/bin/
lstat start-notebook.sh: no such file or directory
```

Any ideas?

**Comment by achapkowski** [comment]
when I do get the server running, I also get this error:
[E 160426 14:02:12 spawnpool:290] Failed to create proxy route to [user/NDvUBzmmjsCr]: HTTP 403: Forbidden

**Comment by achapkowski** [comment]
I solved the issue by using the sci-py docker image and adding my custom python package to that Dockerfile.

**Comment by captainsafia** [comment]
Andrew, I'm glad to see that you've addressed the problem. Apologies I wasn't
able to respond on
time.![](https://link.nylas.com/open/dzqy30d1igqlspctkj1tz54w2/local-38b6594b-
efd4)

On Apr 26 2016, at 1:11 pm, Andrew &lt;notifications@github.com&gt; wrote:  

> I solved the issue by using the sci-py docker image and adding my custom
python package to that Dockerfile.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/jupyter
/tmpnb/issues/235#issuecomment-214833193)![](https://github.com/notifications/
beacon/ABxZybbFglksz4M0KI29vMTLf58_mzzhks5p7lVSgaJpZM4IN2_E.gif)

**Comment by achapkowski** [comment]
@captainsafia no worries, you got me on the correct path.  I'm a total noob to this stuff.
