### ISSUE TITLE
Default allowed number of connections?

### ISSUE THREAD

**Issue by achapkowski** [jupyter/tmpnb#238]
With a vanilla install how many users can connect to a single site?
How do you change that setting?
How do you set a max amount of concurrent users?
Can anyone provide details on how the system scales out?
How much RAM/CPU power is needed for say 50 users, 100 users?

**Comment by captainsafia** [comment]
> With a vanilla install how many users can connect to a single site?

The default size of the pool is 10 containers. This is defined [here](https://github.com/jupyter/tmpnb/blob/master/orchestrate.py#L278).

> How do you change that setting?

You can change the `pool_size` variable when you pass it as a command line argument (`--pool-size`) when running `python orchestrate.py`.

> How do you set a max amount of concurrent users?

Same as above. You can set the `--pool-size` parameter. If you'd like the number of containers available and the number of concurrent users to be different, I think you might be able to configure something in the proxy server, but I'm not entirely sure if this is possible or how it would be done.

> Can anyone provide details on how the system scales out?

tmpnb acts an orchestrator for Docker containers that contain images of the Jupyter Notebook. When a user visits the tmpnb endpoint, a new container is allocated for them in the pool at a special endpoint (`/user/123456789abc`).

> How much RAM/CPU power is needed for say 50 users, 100 users?

You can limit the amount of memory that is available in each container (`--cpu-shares`) that is allocated to the user as well as the CPU shares (`----mem-limit `). You can't really say in advance how much memory or processor power is allocated to a container because it does depend on what is being executed in the container. 

Let me know if you need further explanation on any of the above! 😄

**Comment by achapkowski** [comment]
When I set the `--pool-size=20` in my command, it loads, but I get a 500 error from the proxy.

command:

`docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb -v /var/run/docker.sock:/docker.sock  jupyter/tmpnb python orchestrate.py --image='arcrest/scipy-notebook:v1' --command="ipython notebook --NotebookApp.base_url={base_path} --ip=0.0.0.0 --port {port} --pool-size=20"`


Any suggestions?

**Comment by achapkowski** [comment]
I put the `--pool-size` in the wrong spot


``` 
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb20 -v /var/run/docker.sock:/docker.sock  jupyter/tmpnb python orchestrate.py --pool_size=20 --image='arcrest/scipy-notebook:v1' --command="ipython notebook --NotebookApp.base_url={base_path} --ip=0.0.0.0 --port {port}"
```

**Comment by captainsafia** [comment]
Awesome! Do you have any other questions or can I close the issue?

**Comment by achapkowski** [comment]
all good
